import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';
import type { AddProjectResult, Project, TargetType } from '@shared/ipc-contract';
import { detectTargetType } from './DetectionService';
import { GitService, isValidGitUrl } from './GitService';
import type { ProjectRepository } from './ProjectStore';

function deriveNameFromUrl(url: string): string {
  const last = url.replace(/\.git\/?$/, '').split(/[/:]/).pop();
  return last && last.length > 0 ? last : 'Imported project';
}

/**
 * Anything that keeps its own data scoped to a project and needs to drop
 * it when the project goes - the test plan (areas/cases) today, whatever
 * else earns a project-scoped store later. ProjectService doesn't know
 * what a test plan is; it only knows it has to tell whoever owns one.
 */
export interface ProjectDataOwner {
  removeAllForProject(projectId: string): void;
}

/**
 * Owns "point AutoAI at a project": cloning a git remote or referencing a
 * local folder, then running the (deliberately simple, v1) detection
 * heuristic against it. Every clone destination is generated by us under a
 * workspace root - never a path built from user input - so a crafted
 * project name or URL can't be used for path traversal.
 */
export class ProjectService {
  private readonly git = new GitService();

  constructor(
    private readonly repository: ProjectRepository,
    private readonly workspaceRoot: string,
    private readonly dataOwners: readonly ProjectDataOwner[] = [],
  ) {
    mkdirSync(this.workspaceRoot, { recursive: true });
  }

  public list(): Project[] {
    return this.repository.list();
  }

  public async addFromGit(input: { url: string; branch?: string; name?: string }): Promise<AddProjectResult> {
    const url = input.url.trim();
    if (!isValidGitUrl(url)) {
      return {
        ok: false,
        error: 'INVALID_GIT_URL',
        detail: 'Use a plain https:// URL (no embedded credentials) or an SSH remote like git@host:org/repo.git.',
      };
    }

    const id = randomUUID();
    const destDir = join(this.workspaceRoot, id);

    const outcome = await this.git.clone(url, destDir, input.branch);
    if (!outcome.ok) {
      if (outcome.reason === 'not-installed') {
        return {
          ok: false,
          error: 'GIT_NOT_INSTALLED',
          detail: 'git was not found on this machine. Install Xcode Command Line Tools (`xcode-select --install`) or Git, then try again.',
        };
      }
      // Clean up a partial clone directory so retries don't collide.
      this.safeRemoveDir(destDir);
      return { ok: false, error: 'CLONE_FAILED', detail: outcome.detail };
    }

    const project: Project = {
      id,
      name: input.name?.trim() || deriveNameFromUrl(url),
      source: { type: 'git', url, branch: input.branch ?? null },
      localPath: destDir,
      createdAt: new Date().toISOString(),
      detection: safeDetect(destDir),
      overriddenTargetType: null,
      baseUrl: null,
      testCaseFolderPath: null,
    };

    this.repository.add(project);
    return { ok: true, project };
  }

  public addFromLocalPath(input: { path: string; name?: string }): AddProjectResult {
    const path = input.path.trim();
    if (path.length === 0) {
      return { ok: false, error: 'INVALID_LOCAL_PATH' };
    }
    if (!existsSync(path) || !statSync(path).isDirectory()) {
      return { ok: false, error: 'PATH_NOT_FOUND', detail: `${path} does not exist or is not a folder.` };
    }

    const project: Project = {
      id: randomUUID(),
      name: input.name?.trim() || path.split('/').filter(Boolean).pop() || 'Local project',
      source: { type: 'local', path },
      localPath: path,
      createdAt: new Date().toISOString(),
      detection: safeDetect(path),
      overriddenTargetType: null,
      baseUrl: null,
      testCaseFolderPath: null,
    };

    this.repository.add(project);
    return { ok: true, project };
  }

  public remove(id: string): void {
    const project = this.repository.find(id);
    this.repository.remove(id);
    // Only ever delete files we created (a managed git-clone destination
    // under our own workspace root) - never a local folder the user pointed
    // us at, which they own and expect to keep untouched.
    if (project?.source.type === 'git') {
      this.safeRemoveDir(project.localPath);
    }
    // A test plan describing a project that no longer exists is not a
    // stray record, it's a lie the app would go on telling - so it goes
    // with the project, every time, not only when a caller remembers to.
    // Guarded on `project` existing so an id that was never real doesn't
    // fan out into every data owner as a silent, meaningless no-op call.
    if (project) {
      for (const owner of this.dataOwners) {
        owner.removeAllForProject(id);
      }
    }
  }

  public setOverride(id: string, targetType: TargetType | null): Project | null {
    return this.repository.update(id, { overriddenTargetType: targetType });
  }

  /** Mirrors setOverride exactly - see its own doc. Trimmed to null on an
   *  empty string so clearing the field in the renderer stores an explicit
   *  "not set" rather than an empty-but-truthy string. */
  public setBaseUrl(id: string, url: string | null): Project | null {
    const trimmed = url?.trim() ?? '';
    return this.repository.update(id, { baseUrl: trimmed.length > 0 ? trimmed : null });
  }

  public setTestCaseFolder(id: string, path: string | null): Project | null {
    return this.repository.update(id, { testCaseFolderPath: path });
  }

  public runDetection(id: string): Project | null {
    const project = this.repository.find(id);
    if (!project) return null;
    return this.repository.update(id, { detection: safeDetect(project.localPath) });
  }

  private safeRemoveDir(dir: string): void {
    if (!dir.startsWith(this.workspaceRoot)) return; // never touch anything outside our own workspace
    try {
      rmSync(dir, { recursive: true, force: true });
    } catch {
      // best-effort cleanup only
    }
  }
}

function safeDetect(root: string): Project['detection'] {
  try {
    return detectTargetType(root);
  } catch {
    return null;
  }
}
