import { homedir } from 'node:os';
import type { SystemToolInstallResult } from '@shared/ipc-contract';
import type { EnvironmentProbe } from './EnvironmentCheckService';
import { NodeEnvironmentProbe } from './EnvironmentCheckService';
import type { ProcessSpawner } from './ProjectSetupService';
import { NodeProcessSpawner } from './ProjectSetupService';

/**
 * A small, closed, hardcoded map - binary -> the exact Homebrew formula
 * AutoAI will install for it. Every value here is a literal string this
 * file wrote; none of it is generated by Claude, derived from a target
 * project's own files, or built from renderer input. That's what makes
 * this categorically different from (and safer than) the database/
 * credentials/secrets boundary that stays permanently manual - see the
 * plan this shipped under for the full reasoning.
 *
 * Deliberately excludes tools with no clean, silent, single-command path:
 * Xcode command line tools (`xcode-select --install` pops a system GUI
 * dialog), Flutter and the Android SDK (multi-step installers with their
 * own license-acceptance prompts). Those stay instruction-only, same as
 * before this file existed.
 */
const BREW_FORMULAS: Readonly<Record<string, string>> = {
  php: 'php',
  composer: 'composer',
  python: 'python',
  python3: 'python3',
  ruby: 'ruby',
  dotnet: 'dotnet',
};

/** macOS with Homebrew only for now - installing Homebrew itself is its own
 *  remote-script installer, out of scope. Exported so EnvironmentCheckService
 *  can decide, per item, whether to offer the one-click path at all -
 *  the single source of truth for "is this binary on the safe list,"
 *  never duplicated into a second list anywhere else in this app. */
export function isInstallableBinary(binary: string): boolean {
  return process.platform === 'darwin' && binary in BREW_FORMULAS;
}

/**
 * Runs exactly `brew install <the one hardcoded formula>` for a binary on
 * the closed list above, after confirming Homebrew itself is present -
 * never a general "run brew with whatever name" allowlist. Re-checks the
 * binary's own presence afterward rather than trusting the exit code
 * alone, the same "verify, don't just trust" discipline `ProjectSetupService`
 * already applies to a start command's crash-on-boot check.
 */
export class SystemToolInstaller {
  constructor(
    private readonly spawner: ProcessSpawner = new NodeProcessSpawner(),
    private readonly probe: EnvironmentProbe = new NodeEnvironmentProbe(),
  ) {}

  public async install(binary: string): Promise<SystemToolInstallResult> {
    const formula = BREW_FORMULAS[binary];
    if (!formula || process.platform !== 'darwin') {
      return { ok: false, error: 'NOT_INSTALLABLE' };
    }

    const brewPresent = await this.probe.commandAvailable('brew', ['--version']);
    if (!brewPresent) {
      return { ok: false, error: 'BREW_NOT_FOUND', detail: 'Homebrew was not found on this machine.' };
    }

    let result;
    try {
      result = await this.spawner.runToCompletion(`brew install ${formula}`, homedir());
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      return { ok: false, error: 'INSTALL_FAILED', detail };
    }

    const nowPresent = await this.probe.commandAvailable(binary, ['--version']);
    if (result.exitCode !== 0 && !nowPresent) {
      return { ok: false, error: 'INSTALL_FAILED', detail: result.stderr || result.stdout || `brew exited ${result.exitCode}` };
    }

    return { ok: true, nowPresent, output: result.stdout || result.stderr };
  }
}
